In [51]:
#question1
for x in range(2000,3201):
    if (x%7==0)and(x%5!=0):
        print(x, end=",")
  

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199,

In [52]:
#question2
x=8
y=x
for x in range(1,x):
    x=y*x
    y=x
print(x)    

40320


In [53]:
#question3
x=8
d={}
for y in range(1,x+1):
    d[y]=y*y

print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [54]:
#question4
ch=input("entrer une chaine")
if ch!="":
    m=input("entrer une position")
    m=int(m)
    n=len(ch)
    if (m>=0)and(m<=n):
        ch=ch.replace(ch[m],"",1)
        print(ch)

entrer une chainekitten
entrer une position0
itten


In [55]:
#question5
import numpy as np
arr = np.array([[0,1],[2,3],[4,5]])

print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()

print(f'List: {list1}')


NumPy Array:
[[0 1]
 [2 3]
 [4 5]]
List: [[0, 1], [2, 3], [4, 5]]


In [56]:
#question6
import numpy as np
arr = np.array([0,1,2])
arr2 = np.array([2,1,0])
print("\nOriginal arr:")
print(arr)
print("\nOriginal arr2:")
print(arr2)
print("\nCovariance matrix of the said arrays:\n",np.cov(arr,arr2))


Original arr:
[0 1 2]

Original arr2:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [57]:
#question7
import math 
c=50
h=30
d=input("donnez d : ")
b = d.split(",")
b = [int(i) for i in b]
for x in range (0,len(b)) :
   q=round(math.sqrt((2*c*b[x])/h))
   print(q,end=",")
  

   

donnez d : 100,150,180
18,22,24,